name: Rust Build and Publish

on:
  push:
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true

    - name: Install musl-tools
      run: sudo apt-get update && sudo apt-get install musl-tools

    - name: Build for musl
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target x86_64-unknown-linux-musl

    - name: Publish to GitHub Packages
      uses: actions/upload-artifact@v2
      with:
        name: favify
        path: target/x86_64-unknown-linux-musl/release/favify
